### PR TITLE
`lib/Calendar.js` refactor and new features

### LINKED ISSUE #12: Separation of multiple Optional Memorials falling on one day
In Slovakian calendar (see [this](https://lc.kbs.sk/?den=20180120)), on 20 Jan 2018 we could celebrate either and only one from the following:

1. Feria
2. Optional Memorial of St Fabian
3. Optional Memorial of St Sebastian
4. Votive Holy Mass in Honour to the Blessed Virgin Mary (literally translated as _Optional Memorial of Virgin Mary on Saturday_, for we in Slovakia have on every ferial Saturday this Optional Memorial).

This problem is with the string on the [78](https://github.com/pejulian/romcal/blob/cbf46aff82c85c36ddd848ce70bcbb18466bb137/src/locales/en.mjs#L78) line of `src/locales/en.mjs`, because it combine the two Optional Memorial of Sts Fabian and Sebastian into one.

Please consider to separate them for Slovakian calendar.

### LINKED ISSUE #91: Include default settings in national calendar files
I think a **calendar** file for a specific country should include the **default settings for that country:**
- `christmastideEnds`
- `epiphanyOnJan6`
- `corpusChristiOnThursday`
- `ascensionOnSunday`

These options will remain editable from the romcal API.
But if they are not redefined, will apply first the values defined in the calendar file of the selected country (if exists). 
If they are not either defined in the calendar country file, it will use the romcal default settings (like actually).

The advantage here is that we can select a calendar of any country, without have to know what are the specific rules for that country. They will be applied automatically.

### PR DESCRIPTION
**Pull request by emagnier**
A major code refactoring has been done on the `lib/Calendar.js`.
It was made with the goal of simplifying the code, and make it more robust and extendable (with a few new features in mind). Thanks to this work, 2 new features are already available.

**New features:**
- A day that has only optional celebrations (in addition to the feria) will output all the available celebrations. Previously, only the first optional celebration was output by romcal, without other available celebrations and the feria. (Fix #12)
- Default configuration settings can now be set for each calendar files. This allows for example to enable the `epiphanyOnJan6: true` by default when you select the `slovakia` calendar. Custom configurations are now moved from the romcal core codebase to the calendar files (especially the epiphanyOnJan6 for Slovakia calendar), as well as default romcal options (mostly moved to the `general` calendar). (Fix #91)

**Changes:**
- The parameter and the method to enable/disable converting dates to ISO8601 strings has been removed. It was accessible through the second parameter (or by a unique boolean parameter) on the `romcal.calendarFor()` method. Instead a new property `date` is now always available on each date item object. It contains the date converted to `ISO8601`. Previously this information was available on the `moment` property, which was also used by the `Moment` object. This improvement will avoid converting back multiple time this information (between `ISO8601` string and `Moment` object), avoiding potential typing issues, and keep the `moment` property to a single usage.

**Improvements:**
- [Flow](https://flow.org/en/) have been introduced to this project, with the goal to improve code quality, and particularly type checking. It is enabled with the `// @flow` comment at the beginning of the files we want to monitor. A new build step has been added, and flow typing will be checked by Travis.
- New class/methods have been documented following the JSDoc convention.
- New tests have been added, including for the `drop` feature, the `prioritized` option to date items, and the cases where one or multiple optional memories (or commemorations) are available in addition to the feria.

### CODE REVIEW

**Comment by emagnier** [comment]
PR previously reviewed here: #158, and reopened against the `dev` branch.

**Comment by emagnier** [comment]
This PR just needs approval to be merged. And it got the green light from Travis (although @pejulian is working on another Travis config).

This PR will also fix cases where 2 celebrations were merged behind the same key (using `Or` in the key). 

For example `saintJohnDamascenePriestAndDoctorOrSaintBarbaraVirginAndMartyr` in the Slovak calendar. 
Here it's no longer necessary to drop `saintJohnDamascenePriestAndDoctor`: 
a new `saintBarbaraVirginAndMartyr` can just be added in the Slovak calendar, and the 2 celebrations will be output together by romcal for the same day.

**Comment by pejulian** [comment]
I'm excited to see flow coming into the picture with this PR!
In terms of the code itself, I'll give it a look through but as mentioned earlier, it's going to be some time before I get back into the flow and logic again. So I guess for now, I'll have to lean on the opinion of others.

As for the Travis build, it should work as before only until the feature branch I am working on gets merged to the main fixed branches. I see only minor merge conflicts between the changes I made and the one's in this PR when we finally merge that in to the main branches.

**Comment by tukusejssirs** [comment]
> This PR just needs approval to be merged.

@emagnier, you can request PR approval in the upper right parts of the PR request. :smiley:

> This PR will also fix cases where 2 celebrations were merged behind the same key (using `Or` in the key).

1. You did not fixed the keys in localisation files that does not contain `Or`, but a slash (`/`), therefore it won’t always work.

2. Did you take into account with `Or` that some keys contain this substring, but not in the sense of the word _or_? Quick `grep` showed me the following examples (I have even found some typos with `POrtugal` and `POrtugalReligious`):
- `Order`;
- `Ordinaire`;
- `Ordinario`;
- `Ordinary`;
- `Ordre`;
- `Orione`;
- `OrionePriest`.

**Comment by emagnier** [comment]
@tukusejssirs I wanted to say, "This PR will also allow fixing cases where...". I've corrected my last comment.

@pejulian thanks to offer your time for code review. I didn't want to bother you with that, but if you can do it in time to time like here, it would be awesome 😃

**Pull request merged**
