### PR TITLE
Merge romcal-es6 to master

### PR DESCRIPTION
**Pull request by jarosz**
I have resolved conflicts. Please review especially package-lock.json, because I don't know exactly how it works.

### CODE REVIEW

**Comment by emagnier** [comment]
Please don't do that.

**Comment by emagnier** [comment]
There is still things to do before a release, and we don't want to release it that way.

**Comment by jarosz** [comment]
Ok, so should I commit these small calendar fixes to master?

**Comment by jarosz** [comment]
Please move the discussion about my commits to romcal-contributors. I don't want to make harm.

**Comment by tukusejssirs** [comment]
@jarosz, if you really insist do merge it to `master` **now**, I’d rather suggest to merge it into `jarosz/master` branch than to `romcal/master`. I don’t wanna fight over this, but there is no need to rush.

Why do you want to merge this so fast?

**Comment by emagnier** [comment]
If you really need stuffs very quickly, use your forked repo, in the meantime things are ready here.

**Comment by tukusejssirs** [comment]
@emagnier, @jarosz: continue the conversation [here](https://github.com/orgs/romcal/teams/romcal-contributors)

**Pull request closed without merging**
