### PR TITLE
Add localised keys in `src/locales/skSk.mjs`

### PR DESCRIPTION
**Pull request by tukusejssirs**
I’ve just translated all the strings from `enUs.mjs` into Slovakian.

Currently, there are some differences between `enUs.mjs` and `skSk.mjs`:

| key name (`enUs.mjs`) | key name (`skSk.mjs`) | notes |
|---|---|---|
"blessedHrzonataMartyr" | "blessedHroznataMartyr" | typo in `enUs.mjs`
"jesusChristTheEternalHighPriest" | | duplicate (same key name)
"ourLadyOfFatima" | | duplicate (same key name)
"ourLadyOfLourdes" | | duplicate (same key name)
"ourLadyOfLujanPatronessOfArgentina" | | duplicate (same key name)
"ourLadyOfMountCarmel" | | duplicate (same key name)
"peterAndPaulApostles" | | duplicate (same key name)
"presentationOfTheBlessedVirginMary" | | duplicate (same key name)
"saintAndrewTheApostle" | | duplicate (same key name)
"saintAugustineOfCanterburyBishop" | | duplicate (same key name)
"saintBonifaceBishopAndMartyr" | | duplicate (same key name)
"saintCasimir" | | duplicate (same key name)
"saintCyrilOfJerusalemBishopAndDoctor" | | duplicate (same key name)
"saintElizabethOfHungary" | | duplicate (same key name)
"saintElizabethOfPortugal" | | duplicate (same key name)
"saintFabianPopeAndMartyrAndSaintSebastianPopeAndMartyr"      |	"saintFabianPopeAndMartyrAndSaintSebastianMartyr" | while @pejulian  change the value, but he forgot about the key name, hence the difference
"saintFrancisXavierPriest" | | duplicate (same key name)
"saintGregoryTheGreatPopeAndDoctor" | | duplicate (same key name)
| | "saintHelena" | I added this key; the celebration is to be added yet
"saintHenryBishopAndMartyr" | | duplicate (same key name)
"saintJohnOfKantyPriest" | | duplicate (same key name)
"saintMariaGorettiVirginAndMartyr" | | duplicate (same key name)
"saintPatrickBishop" | | duplicate (same key name)
"saintPeterCanisiusPriestAndDoctor" | | duplicate (same key name)
"saintPiusVPope" | | duplicate (same key name)
"saintRaymondOfPenyafortPriest" | | duplicate (same key name)
| | "saintsFelipeDeJesusPaulMikiAndCompanionsMartyrs" | I left this key because of the unresolved issue #24
| | "saintsPedroBautistaPaulMikiAndCompanionsMartyrs" | I left this key because of the unresolved issue #24
"saintsPhilipAndJamesApostles" | | duplicate (same key name)
"saintStanislausBishopAndMartyr" | | duplicate (same key name)
"saintStephenOfHungary" | | duplicate (same key name)
"saintTeresaBenedictaOfTheCrossEdithSteinVirginAndMartyr" | | duplicate (same key name)
"saintTeresaOfJesusVirginAndDoctorOfTheChurch" | | duplicate (same key name)
"saintThomasBecketBishopAndMartyr" | | duplicate (same key name)
"saintThomasTheApostle" | | duplicate (same key name)
"saintVincentDeaconAndMartyr" | | duplicate (same key name)
"visitationOfTheBlessedVirginMary" | | duplicate (same key name)

Then, I’ve put there some comments:
- all celebrations (except for those from General Roman Calendar) has a comment of calendar (country) name (e.g. unitedStates);
- duplicate keys with different names are notes as `duplicate`;
- joint celebrations (those that needs to be separated, not all) are noted with `to be separated`;
- celebrations that have a different name in some countries, are noted with `localised {key}.[calendarName]` (e.g., `localised {key}.slovakia`)
- sometimes I put there some other comments (like notes for myself in regard of the `skSk.mjs` translation).

I did my best in translation name of the saints, blessed and celebrations which are not yet translated into Slovakian. I might have made some mistakes.

The keys are not yet sorted (issue #18).

### CODE REVIEW

**Comment by tukusejssirs** [comment]
By the way, I used the following one-liner for the key name diff (you need to be in the `src/locales` directory):
```grep "[ ]*\".*\"\: \"" enUs.mjs | sed 's/^[ ]*\(".*"\):.*/\1/g' - | sort > ~/en.diff && grep "[ ]*\".*\"\: \"" skSk.mjs | sed 's/^[ ]*\(".*"\):.*/\1/g' - | sort > ~/sk.diff && diff -y --suppress-common-lines ~/{en,sk}.diff | less && rm ~/{en,sk}.diff```

And for output of keys and comments from a locale file (again, `cd src/locales`):
```grep "[ ]*\".*\"\: \".*\"[,]*[ ]*//" skSk.mjs | sed 's/: \".*\"[,]*//g' -```

**Comment by tukusejssirs** [comment]
Note that before merging this PR, (1) all other locales must change (correct) there keys and (2) also the calendars must be updated to use the new strings.

**Comment by emagnier** [comment]
A big thank you for this great job of translation! 👍 

Also when it's going to be ready, could you [squash](5201642) all your commits into one ? 
So as much as we can we keep a clean commit history.

**Comment by tukusejssirs** [comment]
Okay, I’ll squash ’em all. :) … However, your link does not work, though I know how to do it.

**Comment by emagnier** [comment]
Link fixed 😺, thanks!

**Comment by tukusejssirs** [comment]
I was to eager to merge this PR, however I have forgotten to push my final commit from my computer to GitHub. Now, it is in my fork, however, what should I do?
- Should I revert this merge, and there remerge it with the missing commit?
- Should I create a new PR and then merge it?

**Pull request merged**
