### PR TITLE
Various bugfixes.

### PR DESCRIPTION
**Pull request by jarosz**

### CODE REVIEW

**Comment by emagnier** [comment]
@jarosz Please don't merge PR yourself when there things we should review first.

**Comment by tukusejssirs** [comment]
@jarosz, could you create separate PRs for each bug/issue fix? This PR resembles one of your previous PRs, currently deemed to doom as `romcal/jarosz` branch. This multi-bugfix PR is hard to review.

**Comment by tukusejssirs** [comment]
@emagnier, I reviewed the changes in this PR and I could not find an issue.

However, because @jarosz did not include the `fixes #nnn` in the merge message, those issues where not closed automatically by GitHub.

One issue, non-related to the modified files directly, is that the changes where not recorded in `HISTORY.md`.

I suggest that the merges should be done exclusively by @emagnier as (1) he is currently the maintainer; (2) only one person should create merge commit.

**Comment by emagnier** [comment]
@jarosz Yes we really appreciate your help to fix bugs, but we are working together so you can't open/merge PR like that. This isn't correct.

Also it's important to document what has been fixed, in the description of this PR and the HISTORY.md file.

@tukusejssirs thanks for your review. And thanks for your suggestion about merging things. I think we should try that way.

**Comment by emagnier** [comment]
Also fo the fixed things, we could close the related issues.

**Comment by jarosz** [comment]
Please move the discussion about my commits to romcal-contributors. I don't want to make harm.

**Pull request merged**
