### PR TITLE
Merge last commits from `master` into `dev` branch

### PR DESCRIPTION
**Pull request by emagnier**

### CODE REVIEW

**Comment by tukusejssirs** [comment]
@emagnier, @pejulian: I still think that this should be in the other way around: first commit to `dev`, then to `test` and _finally_ to `master` branch.

**Comment by emagnier** [comment]
@tukusejssirs what's wrong here? It's important to merge back new commits from `master` to `dev` (and `test` when it will exist), because `master` could still receive hotfix or minor changes (like here with theses 2 commits, and such as discussed [here](https://github.com/orgs/romcal/teams/romcal-contributors/discussions/8)). I think still accept small PRs like you made on `master`, will also allow taking our time and test correctly new features from the `dev` branch, without preventing romcal from moving forward for very small things that have no impact on the romcal's behavior, and which could be fixed quickly. However, for next PRs opened against `master`, we could still object to reopen them to `dev` for those we are not confident with what has been modified.

@pejulian I already worked on projects where theses steps were automated (when there is no conflicts). Do you think this could be also automated here at some points?

**Comment by tukusejssirs** [comment]
> @tukusejssirs what's wrong here?

Well, I’ve told you a few times my point of view on the merging _back to `dev`_. I think that @pejulian agrees with me (but I am not sure, therefore we should wait until he tells us his opinion) that we should not merge _back_ to `dev`, but rather merge (tested) changes to `master`. Mind the order and release flow.

I’ve never said the release flow you are used to is wrong. All I do is that I am not really comfortable with it. Now that @pejulian is back I’d like to hear his opinion on this matter. **If he, however, agrees with you, then I won’t talk about this matter anymore.**

> […] because `master` could still receive hotfix or minor changes […] I think still accept small PRs like you made on `master` […].

Yes, I agree, but first I think the changes must be done in the `dev` (and probably `test` if needed) and only then `dev` should be merged into `master` (according to my suggested release flow).

**Comment by emagnier** [comment]
When we will have the opportunity to extract the locales and calendars into a new `romcal-database` repository, I think it will clarify things. Because the `romcal` repo will only contain the core codebase, and these minor fixes will be managed separately from here.

In the meantime, if you prefer we could systematically open PRs on `dev` even for theses small localisation/calendar/typo fixes. But my concern here is why having to wait multiple weeks to get a translation fixed on the `master` channel?
In the incoming weeks, I plan to implement new features we discussed in the issue tracker, which will require for some of them a major code refactor and API changes. So I also want to take time in the dev/test channel to test them and package them well before doing a new release in the stable channel. But everything else also merged into `dev` will have to wait that theses major works get ready before be released to `master`. That reminds me the situation of the `romcal-es6` branch where a lot of localisation and calendars stuff were fixed but we weren't able to release them because the build system and code refactor were not ready yet. As a contributor point of view and a user or romcal, I found that a little frustrating.

However, we could always have to make hotfixes on `master`, it's the life of all development projects. And for theses situation, merging back the commit to `test` and `dev` remain a recommended practice on all similar git workflow. It's important to keep the `dev` branch not too far from the `master` branch (I mean everything on `master` should also be on `test` and `dev`). But before doing hotfixes, we will have to distinguish what is really a hotfix/urgent and what could wait.

So as I've written at the beginning of my comment, the correct answer for everyone might come when the core of romcal and all localisation and calendar data will be isolated in different repositories.

**Comment by pejulian** [comment]
> @tukusejssirs what's wrong here? It's important to merge back new commits from `master` to `dev` (and `test` when it will exist), because `master` could still receive hotfix or minor changes (like here with theses 2 commits, and such as discussed [here](https://github.com/orgs/romcal/teams/romcal-contributors/discussions/8)). I think still accept small PRs like you made on `master`, will also allow taking our time and test correctly new features from the `dev` branch, without preventing romcal from moving forward for very small things that have no impact on the romcal's behavior, and which could be fixed quickly. However, for next PRs opened against `master`, we could still object to reopen them to `dev` for those we are not confident with what has been modified.
> 
> @pejulian I already worked on projects where theses steps were automated (when there is no conflicts). Do you think this could be also automated here at some points?

Hello @emagnier, if I understand you correctly, perhaps a `cron` job could be defined in Travis to do nightly merges from one branch to another that aborts on conflict. I'll look into that and see what I can cook up 😄.

**Comment by emagnier** [comment]
@pejulian yes this is exactly that. If there is a conflict we will do the merge manually.

**Comment by pejulian** [comment]
> > @tukusejssirs what's wrong here?
> 
> Well, I’ve told you a few times my point of view on the merging _back to `dev`_. I think that @pejulian agrees with me (but I am not sure, therefore we should wait until he tells us his opinion) that we should not merge _back_ to `dev`, but rather merge (tested) changes to `master`. Mind the order and release flow.
> 
> I’ve never said the release flow you are used to is wrong. All I do is that I am not really comfortable with it. Now that @pejulian is back I’d like to hear his opinion on this matter. **If he, however, agrees with you, then I won’t talk about this matter anymore.**
> 
> > […] because `master` could still receive hotfix or minor changes […] I think still accept small PRs like you made on `master` […].
> 
> Yes, I agree, but first I think the changes must be done in the `dev` (and probably `test` if needed) and only then `dev` should be merged into `master` (according to my suggested release flow).

Hello @tukusejssirs,

Many great points were raised in this discussion on branching strategy and there's many valid concerns across the table. Absolutely no one is wrong and no one's concerns are not important. I'll try to address these concerns in a way that hopefully everyone can be comfortable with moving forward (at least for now). 

We must remind ourselves that we are a relatively new project and it is only in recent months that the pace is picking up in terms of contributions and collaborators. We are at a point where there are many moving parts in our "ecosystem" that need to be established before the product reaches its first stage of maturity.

In this respect, an agile mindset is what we need where the main goal should be to deliver value to our users.

What @tukusejssirs described definitely falls under the "classic" git flow approach. It is systematic and highly structured and should be considered a standard practice in any matured product offering. The trade offs however are that is it not easy to maintain and we will most likely find ourselves cracking our heads over the right way of merging this or that. Plus with so many branching rules. code conflict resolutions may take a lot of time to resolve. The approach works well for a matured product because changes are well organized and come in a organized manner but we are still some way from reaching that state at present.

As @emagnier has illustrated in his comments above, maintainability issues can cause frustrations to contributors especially during a deep development phase (that I see us currently being in). As such, to support our efforts to "deliver", I have to agree with @emagnier that we should always strive to keep `test` and `dev` as close to `master` as possible to reduce code deviation and merge conflicts (or as they call it in some places:- big bang releases). This should mean a greater speed of delivery, which I believe is our main priority at present.

As we now correctly practice, hot fix branches should be created to address critical issues in `master` as and when needed. These are then PR-ed back to `master` when ready. What we could do in the near future to address @tukusejssirs concerns is to try and merge that hot fix branch to `dev` (and `test) as well especially if the changes are small. That way, we can avoid merging `master` back to `dev` or other branches and strictly obey the rules of classic git flow.

As I see it, we are now in a somewhat hybrid git flow process where we are neither fully compliant to the classic git flow or fully agile (trunk based). To me, this arrangement is just right for our needs as we have some structure in our git flow and also the flexibility to speed things up when needed. I propose that we keep things this way for now to ensure that feature delivery is as smooth as possible.

If this is agreeable, perhaps @tukusejssirs could add a "Git Flow" item in the backlog so that we remember to revisit this process when we are ready.

Here's a diagram that can help visualize this hot fix PR process that we can use in the future (Ignore the parts that are not relevant to us):

git-flow

The only reason that I wouldn't implement the hot fix PR process right now is because I would like to first set up a cron job to merge `master` back to `dev` to ensure hot fixes get back into our development stream ASAP.  Then when we are ready, we can disable this and look at a safer approach.

Do let me know your thoughts! 😄

**Comment by emagnier** [comment]
@pejulian: I deeply agree with you! Thank you for taking the time to share your point of view, and thanks for your communication skills! On my side, writing in English is taking me a lot of time... Trying not to do too many mistakes and share my ideas is a difficult exercise for me in this language. I really prefer to write code 😄 

I know this diagram well, and the article where it comes from. During multiple years I worked on large projects following this git workflow. It was a good experience (especially on large teams), and I'll definitely continue to recommend it!

As you described for romcal, things are a bit different. I started to contribute on it only 3 months ago, this project was sleeping since a long time, and the last version of the codebase required a bit of love to run correctly. At this stage, enforcing practices and procedures too strong and too quickly is just killing efficiency and the motivation (this is why I didn't even share about a hotfix branch, it's clearly too early). We have to go step by step. However since the release of the `1.3` we can see good evolution about continuous integration (a big thank you Julian!).

We have to keep in mind that this project remains a small and a niche project that also need to gain in maturity. So it's important to stay simple and flexible if we want to attract new contributors and don't discourage the existing one.

**Comment by emagnier** [comment]
On a side note, we might also have to create PR on the `test` branch, if we find bugs on a new feature in the testing period (and because the `dev` branch will continue to live accepting new commits). In that case, new commits on `test` should be merged on `dev` as well.

@pejulian do you prefer we merge that PR, or we close it so you can experiment your cron job (if you plan to do it soon)?

**Comment by pejulian** [comment]
> On a side note, we might also have to create PR on the `test` branch, if we find bugs on a new feature in the testing period (and because the `dev` branch will continue to live accepting new commits). In that case, new commits on `test` should be merged on `dev` as well.
> 
> @pejulian do you prefer we merge that PR, or we close it so you can experiment your cron job (if you plan to do it soon)?

I am working on the `cron`. If all goes without issue, I can push it soon. The `cron` will run daily on the `master` branch and attempt to merge code to `dev`. I'll look into a workflow for `test` as well.

In regards to this PR, it all seems good to me. Perhaps, we can wait a bit to hear @tukusejssirs's comments on my views since he requested my views on this subject. 😄

**Comment by pejulian** [comment]
> @pejulian: I deeply agree with you! Thank you for taking the time to share your point of view, and thanks for your communication skills! On my side, writing in English is taking me a lot of time... Trying not to do too many mistakes and share my ideas is a difficult exercise for me in this language. I really prefer to write code 😄
> 
> I know this diagram well, and the article where it comes from. During multiple years I worked on large projects following this git workflow. It was a good experience (especially on large teams), and I'll definitely continue to recommend it!
> 
> As you described for romcal, things are a bit different. I started to contribute on it only 3 months ago, this project was sleeping since a long time, and the last version of the codebase required a bit of love to run correctly. At this stage, enforcing practices and procedures too strong and too quickly is just killing efficiency and the motivation (this is why I didn't even share about a hotfix branch, it's clearly too early). We have to go step by step. However since the release of the `1.3` we can see good evolution about continuous integration (a big thank you Julian!).
> 
> We have to keep in mind that this project remains a small and a niche project that also need to gain in maturity. So it's important to stay simple and flexible if we want to attract new contributors and don't discourage the existing one.

@emagnier, from my perspective, you and @tukusejssirs write English that is really well understood by me (and I am sure by anyone else reading these threads). No complaints from me whatsoever 😆.

**Comment by tukusejssirs** [comment]
It looks that I am too late, as you have discussed this matter in depth. :smiley:

Anyway, I am happy you two have agreed upon the Git flow (and its future progress). I have nothing against anything you both have written. Even my concerns have disappeared! :smiley:

> [@pejulian] If this is agreeable, perhaps @tukusejssirs could add a "Git Flow" item in the backlog so that we remember to revisit this process when we are ready.

Indeed I _can_ create one, but maybe you, @pejulian, can describe it better than me. FYI, @pejulian, the `backlog` is a milestone (although it won’t be closed ever) and all items there are GitHub issues. Currently, we don’t use GitHub projects (though you did in the past), because I don’t find them that useful in the meantime as the milestones are. Although, I don’t think that a Git flow should be decided in public, if we want to add it to `backlog`, it should be a GitHub issue. On the other hand, it might be a good think from the transparency point of view.

---

And back to the topic: I see no problem with this PR. So, if you two have agreed into which branch this PR should be merged, you can merge it.

**Pull request merged**
