### PR TITLE
Add missing feasts to `skSk.mjs`

### PR DESCRIPTION
**Pull request by tukusejssirs**
What I have changed:

- fixed the celebration date of `ourLordJesusChristTheEternalHighPriest`;
- added the celebration of `saintGallAbbotAndMissionary`, `saintFlorianMartyr`, `saintHelena`, and `saintFaustinaKowalskaVirginAndReligious`, `dedicationOfAParticularChurch`, `saintMaurusBishop`;
- raised the celebration type of `allSouls` to memorial (from optional memorial in `general.mjs`);
- updated `saintEmeric` with liturgical colour;
- dropped `saintJohnDamascenePriestAndDoctor` in favour of `saintJohnDamascenePriestAndDoctorOrSaintBarbaraVirginAndMartyr`.

Note that these changes reflect differences between current version of `src/locale/calendars/slovakia.mjs` in `romcal-es6` branch and the same file in the **last commit** in this pull request.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
If you fixed the problem described in the [first comment](https://github.com/pejulian/romcal/issues/21#issue-304183740) of issue #21, then this pull request fixes and closed issue #21.

**Comment by tukusejssirs** [comment]
I have finally finished the rebasing and fixing some issues. Bellow is the full list of changes in the latest commit. There are still two things I’d like do before merging.

### Changes

- remove duplicate key `saintPatrick` (it was defined only in `en.js` and used only in `scotland.js`);
- merge the Slovak translation (`tukusejssirs/ts_add_sk_l10n`) into this one (`tukusejssirs/sk_feasts`), as I have found out that I haven’t rebased `sk_feasts` onto the other branch and it was missing the localised strings;
- remove `ourLadyOfMountCarmelMotherAndQueenOfChile` key as a duplicate of `ourLadyOfMountCarmel`
  - currently, it is defined only in `en.js`, but it is not even used in `chile.js` (it was probably me who removed it some time ago from that calendar);
- I have already localised the optional memorial of Our Lady of Loreto (as [Pope Frances decreed, via the Congregation for Divine Worship and the Discipline](https://www.vaticannews.va/en/church/news/2019-10/feast-of-our-lady-of-loreto-added-to-general-calendar.html); see #106) in `en.js` and `sk.js`; I think the celebration definition (and translation to other locales) should be a separate PR;
- add missing `blessedIstvanSandorMartyr` key to `en.js` (this needs to be added to all other locales except for `sk.js`);
- remove the executable permissions from `it.js` and `italy.js` (I don’t think it is necessary that `*.js` files are executable).

### TODO

- add Sts Cyril and Methodius celebrations (on 14 Feb as OptMem and on 5 Jul as Feast);
- sort the calendar definitions in `slovakia.js`.

**Comment by tukusejssirs** [comment]
Okay, the celebrations are sorted now, but I have no idea what to do with the votive Masses (#110), though I this we should not include them in the calendar for now. If so, review the changes and you can merge it (fixes #21). :smiley:

**Comment by jarosz** [comment]
Merging this as a first step to merge with es6 branch.

**Comment by emagnier** [comment]
@jarosz I know we all want to release this new branch, but please don't merge too fast. This issue was mentioning there is still Todo and I didn't had time to check the question about votive mass.

**Comment by tukusejssirs** [comment]
@jarosz, I agree with @emagnier. What if I have introduced some bugs? The reviews are needed on each and every PR.

@emagnier, yes, there is only one last thing: the votive Masses, though those might not be necessary to be included in the PR.

**Pull request merged**
