### PR TITLE
Merge pull request #144 from emagnier/release

### PR DESCRIPTION
**Pull request by emagnier**
Last step to the `1.3.0` release.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
I see that this PR was force-pushed to `romcal-es6`. I think you should have noted this at least as a comment in this PR, but it would be even better if it would be in the merge description.

**Comment by tukusejssirs** [comment]
Also I think you should have noted this _before_ you merge it to `romcal-es6` and wait at a least a few days until others are notified.

**Comment by emagnier** [comment]
It hasn't been force pushed in the `romcal-es6` branch but only on my working branch (at the time I opened this PR, to fix a typo). So it has no incidence. And this PR is only to summarize what have been done since 1.3.0-beta3, nothing new.

**Comment by tukusejssirs** [comment]
> It hasn't been force pushed in the `romcal-es6` branch but only on my working branch (at the time I opened this PR, to fix a typo). So it has no incidence. And this PR is only to summarize what have been done since 1.3.0-beta3, nothing new.

Yes, you have force-pushed to the `romcal-es6` branch; scroll up this PR on GitHub and you find the note on this (see below the screenshot as a proof).

Screenshot from 2020-01-13 12-34-07

I hope that there won’t be any forced pushes done in the future to the main branch (currently: `romcal-es6`, in a few days: `master`).

---

Note to self and @jarosz: to upgrade `romcal-es6` branches in our forks, we need to overwrite the files in our repos. Therefore do this ([src](https://stackoverflow.com/a/8888015/3408342)):
1. Save all you changes (you can either `stash` them or copy somewhere else in you computer).
2. Check out to `romcal-es6`.
3. Run `git fetch <remote>` to fetch the changes from the `<remote>`. The `<remote>` should the `romcal/romcal` which I have named as `upstream` (`origin` is for me my fork, i.e. `tukusejssirs/romcal`). Alternatively, you could run `git fetch --all` to fetch from all remotes. Note that you must have added the `upstream` remote before fetching the remote(s), else you would not fetch the changes from `romcal/romcal` repo.
4. Run `git reset --hard <remote>/romcal-es6`.
5. Run `git push -f` or `git push -f <remote>` where `<remote>` is you fork (`jarosz/romcal`) usually named as `origin`. This will force-push the changes to your forked repo.
6. Then, any branches based on the old version (commit) of `romcal-es6` should be rebased (`git rebase <remote>/romcal-es6`, where remote is the upstream remote) if you wish (later on) to merge with `romcal-es6` branch in `romcal/romcal` repo.

**Comment by tukusejssirs** [comment]
@emagnier, I think the forced-push was made by 6e0276708087af82f2d59620d936041547a5cfe7 commit, but I could not find a PR for this—did you push it directly from the terminal / command-line?

**Comment by emagnier** [comment]
The Github indication mention the `emagnier/release` branch.

As we discussed already in multiple places, I'm currently working on the release of `1.3.0`, so the actual romcal-es6 branch is now prepared to be merged in the main master branch. Other issues have been postponed to v1.3.1, v2 or moved back to the back-log as you suggested. So then we will be able to do finally an official npm release, and move forward on the next romcal challenges. The `romcal-es6` branch has been rebased on master to prepare the release, and `romcal-es6` will be deleted after the release.

**Comment by tukusejssirs** [comment]
Yes, I know that your are _working_ on the `v1.3.0` relase, but I’d like to see a PR first to review it.

Otherwise, I am okay with everything you say, but the process you choose is not welcome by me. You have not created a PR to rebase `romcal-es6` and/or waited a few day to make a review, and even probably pushed directly to `romcal-es6` branch.

I thought we agreed that **_all_** changes should be made in the forked repo, then create a PR, wait for review, merge when reviewed. I know that I cannot make a deep review of the code as I am not that good programmer, but I’d to give some input. Also, I am not able to do some work on `romcal` every day, so a few days (like 2 to 4 days) review wait time would be great. :smiley:

**Comment by emagnier** [comment]
The PR you wish is already here #145, containing the rebased `romcal-es6`, now ready to be merge in `master` 🎉. But since this PR contain stuffs already reviewed, it's not necessary to review it again.

And you are completely right, I could have used another branch to open this PR, I'm sorry for that, I didn't think about it given that romcal-es6 will be then deleted (since it have no reason for being and would makes confusion).

**Comment by tukusejssirs** [comment]
No, the PR I wish not #145 (`romcal-es6` merged into `master`), but one that would request a merge from one of your branches (a branch in `emagnier/romcal` repo) into `romcal-es6`.

> I didn't think about it given that `romcal-es6` will be then deleted

Yes, indeed it **_will_** be deleted, but until it is not merged into `master`, it is still the _main branch_ as treated as such. After #145 is merged, the `master` branch will be the _main branch_ and `romcal-es6` (a possible even `jarosz` branch) will be removed and all future PRs/MRs will be done against `master` branch. On this we agree. :smiley:

**Comment by emagnier** [comment]
you are just rephrasing all my words 😄

**Comment by tukusejssirs** [comment]
@emagnier, I rather rephrase words of other people (in conversations) to be sure I have understood the words the way they (the people) wanted me to understand those words. Thus, when I misunderstand them, they (the people) would note that immediately and not only after some time during which I might have based some other stuff (like ideas or changes in a code) on something the other party did not wanted me to understand. :smiley:

Nevermind, I am glad we have understood each other. :smiley:

**Pull request merged**
