### PR TITLE
Remove some duplicate keys in `enUs.mjs`; Fix #35

### LINKED ISSUE #35: typo: change `blessedHrzonataMartyr` to `blessedHroznataMartyr
While (still) translating the keys in `skSk.mjs`, I’ve just found out that you have typo in the name and value of `blessedHrzonataMartyr` (see [Hroznata](https://cs.wikipedia.org/wiki/Hroznata) article on Czech Wiki).

My suggestion is to change key and its value to the following:
```bash
"blessedHroznataMartyr": "Blessed Hroznata, Martyr"
```

### PR DESCRIPTION
**Pull request by tukusejssirs**
I added heart emoticon to all my comments which I have fixed with this pull request (in issue #10).

I modified only `src/locale/enUs.mjs` and `src/calendars/{czechRepublic,general,unitedStates}.mjs`. Hopefully, those were enough.

Fixes #35 (typo: change `blessedHrzonataMartyr` to `blessedHroznataMartyr`),
Removes some (all the same key name) duplicates from #10.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
Merge will require change of the keys in `src/caendars/*mjs`.

**Comment by tukusejssirs** [comment]
I have rebased this PR on top of current version of `romcal-es6`.

Changes in the PR:
- use `saintsFabianPopeAndSebastianMartyrs` key everywhere:
   - `en.js`;
   - `fr.js`;
   - `pl.js`;
   - `sk.js`;
   - `general.js`;
- use `saintJohnOfKantyPriest` key everywhere:
   - `en.js`;
   - `fr.js`;
   - `pl.js`;
   - `sk.js`;
   - `general.js`;
   - `poland.js`
- use `blessedHroznataMartyr` key everywhere:
   - `sk.js`;
   - `en.js`;
   - `czechRepublic.js`;
- remove duplicates of `saintElizabethOfPortugal`, `presentationOfTheBlessedVirginMary`, `saintNicholasBishop`, `ourLadyOfLujanPatronessOfArgentina`, `saintPatrickBishop`, `saintRaymondOfPenyafortPriest`, `saintsPhilipAndJamesApostles`, `saintTeresaBenedictaOfTheCrossEdithSteinVirginAndMartyr`, `saintCasimir`, `saintStanislausBishopAndMartyr`;
- remove unnecessary comments:
   - `poland.js`.

I did not make any change in `dist/romcal.bundle.min.js` yet. If I should make the changes in there, just write a comment. :smiley:

**Comment by emagnier** [comment]
Yes, everything is bundled in the `dist/romcal.bundle.min.js` for front-end usage, so you should do a `npm run build` to get the frontend lib in sync on the backend code.

Other than that: 👍

**Comment by emagnier** [comment]
In fact depending of our pull request, the `dist/romcal.bundle.min.js` might be not always sync.
So this is something that we should take care when we publish a new version. Not on every PRs. So let's merge this one ;)

Other than that, in our branch if we need the fresh frontend library from the last commits, we could always do a `npm run build`.

**Comment by tukusejssirs** [comment]
> Yes, everything is bundled in the dist/romcal.bundle.min.js for front-end usage, so you should do a npm run build to get the frontend lib in sync on the backend code.

I know how to build it, but now I’m thinking: why is the `romcal.bundle.min.js` in the repo anyway? Should it not be considered as an _artifact_ of a release?

**Comment by emagnier** [comment]
Yes it's a good idea to move it away from the repo.

**Comment by tukusejssirs** [comment]
> Yes it's a good idea to move it away from the repo.

I we’d use two branch development (stable and dev branch; not counting the feature branches if any), we could use CI/CD to automatically create new releases, artifacts, tags (with version numbers), versioning _when a (any) commit is pushed to the stable branch_. But I know you are (kind of) againt the dev branch. :smiley:

**Comment by emagnier** [comment]
Or more simply, it could be generated automatically on a `npm install` and/or on a git tag event.

I already used dev branch on some projects, and also some other development & cycle branch methods.
It might be change here, if we are too many contributors, but in the meantime I don't really see a a real advantage. Actually we have a too big feature branch with too many things inside (romcal-es6) that need a lot of effort to make it out. Then I hope we will return to a more simple way to contribute on romcal. I currently have little time to contribute, but it might not going to last (depending of my other projects).

**Comment by tukusejssirs** [comment]
> […] but it might not going to last […]

What do you mean by this? Are expecting that you _will_ or _will not_ have enough time to contribute to `romcal`?

**Comment by emagnier** [comment]
romcal is still a project I want to contribute anyway. Actually one of my projects is based on romcal (app for the Liturgy of Hours from a monastic community) and it give me a good opportunity to contribute more, but I don't know yet how this project will progress (everything's not depend on me), and my spare time is also a bit limited.

**Pull request merged**
