### PR TITLE
Update package-lock to 1.3.0

### PR DESCRIPTION
**Pull request by emagnier**
@tukusejssirs oops we forgot to update the package-lock.js

This is minor, but as soon as it's merged, I'll publish a new version on npm.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
I think you should use `git commit --amend` in order to have same code in GitHub release and `npm` release.

**Comment by emagnier** [comment]
It's too late, the merge is done and we can't play easily on the master branch (this branch is protected). We will take care of that next time.

**Comment by tukusejssirs** [comment]
I know it’s protected. But if we don’t want to amend it, should we not release `1.3.1` in both GitHub and `npm`?

**Comment by emagnier** [comment]
npm isn't published yet, and it's very minor so let's merge this PR and release romcal

**Comment by emagnier** [comment]
What do you want to add more in the description?

**Comment by tukusejssirs** [comment]
> @tukusejssirs oops we forgot to update the package-lock.js
> 
> This is minor, but as soon as it's merged, I'll publish a new version on npm.

GitHub will (usually) add the quoted text as merge description. You should either edit or remove the PR description (your first comment).

**Comment by emagnier** [comment]
This is not the case on my side. It refer to my first (and unique) commit name. Ok let's merge it.

**Pull request merged**
