### PR TITLE
Add celebrations for Chinese region (fixes #118)

### LINKED ISSUE #118: Add (group) calendar for China, Hong Kong and Taiwan
We could add this calendar based on [Wiki](https://en.wikipedia.org/wiki/General_Roman_Calendar#China,_Hong_Kong_and_Taiwan).

### PR DESCRIPTION
**Pull request by jarosz**
Based on Wikipedia article: https://en.wikipedia.org/wiki/General_Roman_Calendar#China,_Hong_Kong_and_Taiwan

### CODE REVIEW

**Comment by tukusejssirs** [comment]
@emagnier, what do you think? Should we create a _group calendar_ (see #48) like this?

I don’t say that @jarosz’ work is bad—indead it’s awesome!—but we must look at the issues from higher perspective.

So, my question is: what should we do?
1. Should we wait with this PR/issue until we implement the _group calendars_?
2. Should we create three separate calendars for China, Hong Kong, and Taiwan?
3. Should we merge this PR as is (after reviews)?

**Comment by jarosz** [comment]
I have no way to confirm validity of the Wiki article. For sure it needs clarification with Augustine Zhao Rong solemnity and memorial. Even with these inaccuracies, I think we can treat it as a reference, because it has a wider audience than romcal. You can correct Wiki with your findings.

Translation: I can do Polish myself, there's obviously no official translation.

**Comment by emagnier** [comment]
If this calendar cover the China, Hong-Kong and Taiwan regions, we might rename `china.js` to `chinaHongKongTaiwan.js` to make it more explicit.

@tukusejssirs When #48 will be implemented, we will be able to leverage this calendar at that time.

Translations other than English are only a nice to have, so it's not necessary to add them in this PR (but @jarosz you still can add Polish translations here if you want to do them).

Except the file to rename, for me it's a LGTM.

**Comment by jarosz** [comment]
I don't know if you're familiar with situation of the Church in China. Let's say it's not certain whether China, Taiwan and Hong-Kong should be treated as a whole or separate entities. I'd stick with china.js (maybe chinese.js, since the data is taken from Chinese Regional Bishops' Conference of Taiwan).

**Comment by tukusejssirs** [comment]
Okay, let’s keep it the way it currently is.

@emagnier, I know that it is nice to have all keys localised, but I do my best to cover all the keys. Just for demonstration, the number of localised keys in each _main_ locale is as follows (note that this counts also keys like `season` or `day`):

```bash
$ wc -l [a-z][a-z].js
     5 cs.js
   724 en.js
   298 fr.js
   256 it.js
   306 pl.js
   723 sk.js  # This one will contain 724 (as `en.js`) when PR #127 will be merged)
```

So, I think that when you two, @emagnier and @jarosz, will have some time, you could search the Internet for the remaining keys. I did this last year for `sk.js`, it took some time, but I look forward to look at your ‘full’ locale translation. Again: I know that this is not the priority number one. :smiley:

**Comment by emagnier** [comment]
> I don't know if you're familiar with situation of the Church in China.

@jarosz: No, I'm not too familiar with this situation. Ok, thanks for your suggestion.

> I know that it is nice to have all keys localised

@tukusejssirs: I was just talking about English locales (by suggesting what you already wrote elsewhere). Personally, I'm trying to find enough time to work on romcal presently, so for now I'll not be able to do more on localizing keys in French, unfortunately. If a calendar has already all its keys localized in the speaking language of its country, I prefer then to focus on features instead of taking time to translating everything.

**Pull request merged**
